[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
combine_as_imports = true
known_first_party = ["api", "config"]
skip_gitignore = true

[tool.black]
line-length = 88
target-version = ['py39']
skip-string-normalization = true
